### ISSUE TITLE
도어락 설치시 초기 설정 softAP 가능 여부 조사

### ISSUE THREAD

**Issue by monibu1548** [All-door/Artik_internal_controller#14]
도어락 설치시 마스터비밀번호,

인터넷과 연결하기 위한 wifi, ssid, password

를 입력 받을 수 있는 기능 softAP 를 통해 구현 가능할지 여부 조사

-> 설정용 안드로이드 앱 없이 설정 가능하게 하기 위함

**Comment by monibu1548** [comment]
@InhoChoi  @NayongLee 

1차 softAP 기능 구현 완료  https://github.com/All-door/Artik_internal_controller/pull/18

**Comment by InhoChoi** [comment]
인터넷은 그냥 ethernet 하는거 아니였나영
그리고 softAP를 이용하여 DeviceId 와 고유 비밀번호 설정으로 알고 있엇는데 ㅋㅋ 뭔가 바뀐 느낌

**Comment by monibu1548** [comment]
Device Id랑 고유비밀번호때문에 softAP를 시작했는데

한번 구현해두면 항목은 다 갖다 붙이기만 하면 되는거라

추가해봤슴다

**Comment by InhoChoi** [comment]
넹넹넹

**Comment by monibu1548** [comment]
구현완료
